# Generated by Django 4.2.4 on 2023-08-04 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="user",
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
