# Generated by Django 4.2.4 on 2023-08-05 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Tracker", "0002_remove_company_user_employee_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="created",
        ),
        migrations.AddField(
            model_name="company",
            name="created_by",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
