# Generated by Django 4.2.4 on 2023-08-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0003_remove_company_created_company_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
    ]
