# Generated by Django 4.2.4 on 2023-08-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0004_remove_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="category",
            field=models.CharField(
                choices=[
                    ("Laptop", "Laptop"),
                    ("Tablet", "Tablet"),
                    ("Smartphone", "Smartphone"),
                ],
                default="Laptop",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[("available", "available"), ("unavailable", "unavailable")],
                default="available",
                max_length=50,
            ),
        ),
    ]
