# Generated by Django 4.2.4 on 2023-08-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0005_device_category_device_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="name",
            new_name="model",
        ),
    ]
