# Generated by Django 4.2.4 on 2023-08-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0006_rename_name_device_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="condition",
        ),
    ]
