# Generated by Django 4.2.4 on 2023-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0007_remove_device_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicelog",
            name="checkout_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
